name: CI
on: [push]

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.preset }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        preset: [debug, release]

    steps:
      - name: Install missing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev libtbb-dev
          sudo update-alternatives --set gcc /usr/bin/gcc-10
        if: runner.os == 'Linux'

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
          vulkan-use-cache: true

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake+vcpkg+Ninja to generate/build.
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: ninja-multi-vcpkg-${{ matrix.preset }}
